project_id = "zcjzeafelunqxmxzznos"

[functions.get-team-stats]
verify_jwt = false

[functions.calculate-team-prices]
verify_jwt = false

[functions.calculate-fantasy-scores]
verify_jwt = false

[functions.public-image-proxy]
verify_jwt = false

[functions.share-proxy]
verify_jwt = false

[functions.schedule-match-notifications]
verify_jwt = false

[functions.send-match-reminder]
verify_jwt = false

[functions.award-fantasy-winners]
verify_jwt = false

[functions.process-finished-rounds]
verify_jwt = false

[functions.create-private-round]
verify_jwt = true

[functions.join-private-round]
verify_jwt = true

[functions.generate-welcome-assets]
verify_jwt = false

[functions.set-team-swap]
verify_jwt = true

[functions.get-team-match-breakdown]
verify_jwt = false

[functions.create-round-entry-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.testusersfantasypicks]
verify_jwt = false

[functions.send-affiliate-notification]
verify_jwt = false

[functions.send-affiliate-approval]
verify_jwt = false

[functions.send-affiliate-rejection]
verify_jwt = false

[functions.track-pageview]
verify_jwt = false
