project_id = "zcjzeafelunqxmxzznos"

[functions.get-team-stats]
verify_jwt = false

[functions.calculate-team-prices]
verify_jwt = false

[functions.public-image-proxy]
verify_jwt = false

[functions.share-proxy]
verify_jwt = false

[functions.schedule-match-notifications]
verify_jwt = false

[functions.send-match-reminder]
verify_jwt = false

[functions.award-fantasy-winners]
verify_jwt = false

[functions.process-finished-rounds]
verify_jwt = false

[functions.create-private-round]
verify_jwt = true

[functions.join-private-round]
verify_jwt = true

[functions.generate-welcome-assets]
verify_jwt = false
